symptom_mapping = {
    # ===== Skin-related =====
    "itching": "itching",
    "itchy": "itching",
    "skin rash": "skin_rash",
    "rash": "skin_rash",
    "rashes": "skin_rash",
    "hives": "skin_rash",
    "nodal eruptions": "nodal_skin_eruptions",
    "skin bumps": "nodal_skin_eruptions",
    "skin lumps": "nodal_skin_eruptions",
    "internal itching": "internal_itching",
    "skin peeling": "skin_peeling",
    "dry skin": "skin_peeling",
    "silver scaling": "silver_like_dusting",
    "scales on skin": "silver_like_dusting",
    "silver like dusting": "silver_like_dusting",
    "blackheads": "blackheads",
    "pimples": "pus_filled_pimples",
    "acne": "pus_filled_pimples",
    "scabs": "scurring",
    "blister": "blister",
    "blisters": "blister",
    "red sore around nose": "red_sore_around_nose",
    "yellow crust ooze": "yellow_crust_ooze",

    # ===== Respiratory / ENT =====
    "continuous sneezing": "continuous_sneezing",
    "sneezing nonstop": "continuous_sneezing",
    "cough": "cough",
    "dry cough": "cough",
    "productive cough": "phlegm",
    "phlegm": "phlegm",
    "runny nose": "runny_nose",
    "stuffy nose": "congestion",
    "congestion": "congestion",
    "blocked nose": "congestion",
    "sinus pressure": "sinus_pressure",
    "throat irritation": "throat_irritation",
    "throat pain": "throat_irritation",
    "patches in throat": "patches_in_throat",
    "watering eyes": "watering_from_eyes",
    "red eyes": "redness_of_eyes",
    "eye redness": "redness_of_eyes",

    # ===== General / Systemic =====
    "fever": "high_fever",
    "high fever": "high_fever",
    "mild fever": "mild_fever",
    "chills": "chills",
    "shivering": "shivering",
    "fatigue": "fatigue",
    "tired": "fatigue",
    "tiredness": "fatigue",
    "lethargy": "lethargy",
    "malaise": "malaise",
    "weakness": "weakness_in_limbs",
    "muscle weakness": "muscle_weakness",
    "muscle pain": "muscle_pain",
    "cramps": "cramps",
    "dizziness": "dizziness",
    "spinning": "spinning_movements",
    "vertigo": "spinning_movements",
    "loss of balance": "loss_of_balance",
    "unsteady": "unsteadiness",
    "loss of consciousness": "altered_sensorium",
    "confusion": "altered_sensorium",
    "coma": "coma",
    "dehydration": "dehydration",
    "sweating": "sweating",
    "restlessness": "restlessness",
    "irritability": "irritability",
    "depression": "depression",
    "anxiety": "anxiety",
    "toxic look": "toxic_look_(typhos)",
    "yellowing of eyes": "yellowing_of_eyes",
    "yellow skin": "yellowish_skin",
    "dark urine": "dark_urine",
    "yellow urine": "yellow_urine",
    "loss of appetite": "loss_of_appetite",
    "no appetite": "loss_of_appetite",
    "excessive hunger": "excessive_hunger",
    "increased appetite": "increased_appetite",

    # ===== Pain-related =====
    "joint pain": "joint_pain",
    "pain in joints": "joint_pain",
    "muscle pain": "muscle_pain",
    "neck pain": "neck_pain",
    "back pain": "back_pain",
    "knee pain": "knee_pain",
    "hip pain": "hip_joint_pain",
    "stiff neck": "stiff_neck",
    "stiffness": "movement_stiffness",
    "swelling in joints": "swelling_joints",
    "swollen joints": "swelling_joints",
    "chest pain": "chest_pain",
    "chest tightness": "chest_pain",
    "abdominal pain": "abdominal_pain",
    "stomach ache": "stomach_pain",
    "belly pain": "belly_pain",
    "stomach pain": "stomach_pain",
    "pain in abdomen": "abdominal_pain",
    "belly bloated": "distention_of_abdomen",
    "pain during bowel movements": "pain_during_bowel_movements",
    "pain in anus": "pain_in_anal_region",
    "rectal pain": "pain_in_anal_region",
    "pain while walking": "painful_walking",

    # ===== Digestive =====
    "acidity": "acidity",
    "acid reflux": "acidity",
    "indigestion": "indigestion",
    "nausea": "nausea",
    "vomiting": "vomiting",
    "throwing up": "vomiting",
    "diarrhea": "diarrhoea",
    "loose motion": "diarrhoea",
    "constipation": "constipation",
    "hard stools": "constipation",
    "stomach bleeding": "stomach_bleeding",
    "bloated stomach": "swelling_of_stomach",
    "gas": "passage_of_gases",
    "passing gas": "passage_of_gases",

    # ===== Urinary =====
    "burning urination": "burning_micturition",
    "painful urination": "burning_micturition",
    "spotting during urination": "spotting_ urination",
    "frequent urination": "continuous_feel_of_urine",
    "urinary urgency": "continuous_feel_of_urine",
    "bladder discomfort": "bladder_discomfort",
    "foul smell urine": "foul_smell_of urine",
    "dark pee": "dark_urine",

    # ===== Neurological / Senses =====
    "headache": "headache",
    "migraine": "headache",
    "pain behind eyes": "pain_behind_the_eyes",
    "blurred vision": "blurred_and_distorted_vision",
    "distorted vision": "blurred_and_distorted_vision",
    "loss of smell": "loss_of_smell",
    "slurred speech": "slurred_speech",
    "lack of concentration": "lack_of_concentration",
    "visual disturbance": "visual_disturbances",

    # ===== Cardio / Blood =====
    "fast heartbeat": "fast_heart_rate",
    "palpitations": "palpitations",
    "breathlessness": "breathlessness",
    "shortness of breath": "breathlessness",
    "chest pressure": "chest_pain",
    "bruising": "bruising",
    "swollen veins": "swollen_blood_vessels",
    "prominent veins": "prominent_veins_on_calf",
    "swollen legs": "swollen_legs",

    # ===== Metabolic / Endocrine =====
    "weight loss": "weight_loss",
    "weight gain": "weight_gain",
    "obesity": "obesity",
    "enlarged thyroid": "enlarged_thyroid",
    "cold hands and feet": "cold_hands_and_feets",
    "brittle nails": "brittle_nails",
    "small dents in nails": "small_dents_in_nails",
    "inflammatory nails": "inflammatory_nails",
    "swollen face": "puffy_face_and_eyes",
    "puffy eyes": "puffy_face_and_eyes",
    "swollen extremities": "swollen_extremeties",

    # ===== Liver / Gastro =====
    "acute liver failure": "acute_liver_failure",
    "history of alcohol": "history_of_alcohol_consumption",
    "fluid overload": "fluid_overload",
    "abdominal swelling": "swelling_of_stomach",

    # ===== Reproductive =====
    "abnormal menstruation": "abnormal_menstruation",
    "period problem": "abnormal_menstruation",

    # ===== Infections / Blood =====
    "red spots on body": "red_spots_over_body",
    "discolored patches": "dischromic _patches",
    "yellow patches": "dischromic _patches",
    "family history": "family_history",
    "blood in sputum": "blood_in_sputum",
    "mucoid sputum": "mucoid_sputum",
    "rusty sputum": "rusty_sputum",
    "receiving transfusion": "receiving_blood_transfusion",
    "unsterile injection": "receiving_unsterile_injections",
}
